// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBook = "books"

// Book mapped from table <books>
type Book struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name             string    `gorm:"column:name" json:"name"`
	CategoryID       int32     `gorm:"column:category_id;not null" json:"category_id"`
	AuthorID         int32     `gorm:"column:author_id" json:"author_id"`
	SourceID         int32     `gorm:"column:source_id;not null" json:"source_id"`
	SourceURL        string    `gorm:"column:source_url" json:"source_url"`
	LastChapterTitle string    `gorm:"column:last_chapter_title" json:"last_chapter_title"`
	LastChapterURL   string    `gorm:"column:last_chapter_url" json:"last_chapter_url"`
	CreatedAt        time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt        time.Time `gorm:"column:updatedAt;default:CURRENT_TIMESTAMP" json:"updatedAt"`
	DeletedAt        time.Time `gorm:"column:deletedAt" json:"deletedAt"`
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
